// in this page we can add many songs we want:

let allMusic = [
  {
    name: "Love Like This",
    artist: "Zayn Malik",
    img: "image1",
    src: "music1",
  },
  {
    name: "Pillow Talk",
    artist: "Zayn Malik",
    img: "image2",
    src: "music2",
  },
  {
    name: "Dusk Till Dawn",
    artist: "Zayn Malik",
    img: "image3",
    src: "music3",
  },
  {
    name: "Let Me",
    artist: "Zayn Malik",
    img: "image4",
    src: "music4",
  },
  {
    name: "Like I Would",
    artist: "Zayn Malik",
    img: "image5",
    src: "music5",
  },
  {
    name: "Shinunoga E-Wa",
    artist: "Fuji Kaze",
    img: "image6",
    src: "music6",
  },
  {
    name: "Heartbreak Anniversary",
    artist: "Giveon",
    img: "image7",
    src: "music7",
  },
  {
    name: "The Box",
    artist: "Roddy Ricch",
    img: "image8",
    src: "music8",
  },
  {
    name: "Heat waves - Rock band",
    artist: "Glass Animals",
    img: "image9",
    src: "music9",
  },
  {
    name: "Summertime Sadness",
    artist: "Lana Del Rey",
    img: "image10",
    src: "music10",
  },
  {
    name: "After Hours",
    artist: "The Weeknd",
    img: "image11",
    src: "music11",
  },
  {
    name: "Infinity",
    artist: "Jaymes Young",
    img: "image12",
    src: "music12",
  },
  {
    name: "I wanna Be Yours",
    artist: "Artic Monkeys",
    img: "image13",
    src: "music13",
  },
  {
    name: "No idea",
    artist: "Don Toliver",
    img: "image14",
    src: "music14",
  },
  {
    name: "Drag Me Down",
    artist: "One Direction",
    img: "image15",
    src: "music15",
  },
  {
    name: "Stereo Hearts - Gym Class Heroes",
    artist: "Adam Levine",
    img: "image16",
    src: "music16",
  },
  {
    name: "Often Slowed Reverb - RH Music",
    artist: "Eduardo Luzquinos",
    img: "image17",
    src: "music17",
  },
  {
    name: "Nothing is Lost - Avatar-2",
    artist: "The Weeknd",
    img: "image18",
    src: "music18",
  },
  {
    name: "Call Out My Name",
    artist: "The Weeknd",
    img: "image19",
    src: "music19",
  },
  {
    name: "Die For You",
    artist: "The Weeknd",
    img: "image20",
    src: "music20",
  },
  {
    name: "No Lie",
    artist: "Dua Lipa - Sean Paul",
    img: "image21",
    src: "music21",
  },
  {
    name: "Six Days",
    artist: "DJ Shadow - Mos Def",
    img: "image22",
    src: "music22",
  },
  {
    name: "One Kiss",
    artist: "Dua Lipa",
    img: "image23",
    src: "music23",
  },
  {
    name: "See You Again",
    artist: "Wiz Khalifa - Charlie Puth",
    img: "image24",
    src: "music24",
  },
  {
    name: "The Nights",
    artist: "Avicii",
    img: "image25",
    src: "music25",
  },
  {
    name: "Love Nwantiti",
    artist: "Ckay",
    img: "image26",
    src: "music26",
  },
];
